services:
  frankenphp:
    build:
      context: .
      args:
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME}
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HOST_USER_ID=$HOST_USER_ID
      - HOST_USER_NAME=$HOST_USER_NAME
      - HOST_GROUP_ID=$HOST_GROUP_ID
      - HOST_GROUP_NAME=$HOST_GROUP_NAME
    env_file:
      - .env
  workspace:
    build:
      context: docker/workspace
      args:
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME}
    volumes:
      - .:/app
    environment:
      - HOST_USER_ID=$HOST_USER_ID
      - HOST_USER_NAME=$HOST_USER_NAME
      - HOST_GROUP_ID=$HOST_GROUP_ID
      - HOST_GROUP_NAME=$HOST_GROUP_NAME
    env_file:
      - .env
